import React, { useState } from 'react';
import {
  BasisTheoryProvider,
  useBasisTheory,
} from '@basis-theory/basis-theory-react';
import {
  Container,
  createTheme,
  CssBaseline,
  Grid,
  ThemeProvider,
} from '@mui/material';
import Head from 'next/head';
import { CardForm } from '../components/CardForm';
import { DisplayCard } from '../components/DisplayCard';

const theme = createTheme({
  palette: {
    mode: 'light',
    background: {
      default: '#F9F9FF',
    },
    text: {},
    secondary: {
      main: '#4A4D5F',
    },
    grey: {
      '300': '#8C90A4',
    },
  },
  typography: {
    caption: {
      fontWeight: 500,
      fontSize: '12px',
      lineHeight: '18px',
    },
  },
});

const Home = () => {
  const [tokenId, setTokenId] = useState<string>();

  const { bt } = useBasisTheory(
    process.env.NEXT_PUBLIC_BASIS_THEORY_PUBLIC_KEY as string,
    {
      elements: true,
    }
  );

  return (
    <BasisTheoryProvider bt={bt}>
      <Head>
        <title>{'Basis Theory'}</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <Container component="main">
          <Grid
            alignItems="center"
            container
            direction="column"
            justifyContent="center"
            sx={{ height: '100vh' }}
          >
            <Grid item>
              <CardForm onTokenize={({ id }) => setTokenId(id)} />
            </Grid>
            <Grid item mt={10} position="relative">
              <DisplayCard tokenId={tokenId} />
            </Grid>
          </Grid>
        </Container>
      </ThemeProvider>
    </BasisTheoryProvider>
  );
};

export default Home;
